name: salah_tv
description: Islamic prayer times display for Android TV / TV Box
version: 1.0.3+3
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.5+1

  # Persistent key-value storage
  shared_preferences: ^2.5.4

  # Audio playback for Adhan
  audioplayers: ^6.5.1

  # Hijri calendar conversion
  hijri: ^3.0.0

  # Date/time formatting
  intl: ^0.20.2

  # Arabic fonts (Cairo)
  

  # Save CSV copy to app directory
  path_provider: ^2.1.5

  # Keep screen awake during app usage
  wakelock_plus: ^1.2.9

  # HTTP requests for Quran API
  http: ^1.2.2

  # Makkah live stream
  video_player: ^2.9.3
  dio: ^5.9.2
  package_info_plus: ^9.0.0
  install_plugin_v2: ^1.0.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  get_it: ^9.2.1
  injectable: ^2.7.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.12.2
  injectable_generator: ^2.12.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/adhan.mp3
    - assets/audio/dua.mp3
    - assets/audio/iqama.mp3
    - assets/audio/adhan2.mp3
    - assets/csv/prayer_times.csv
    - assets/csv/uae_prayer_times_2026.csv
    - assets/csv/oman_prayer_times_2026.csv
    - assets/csv/saudi_prayer_times_2026.csv
    - assets/csv/kuwait_prayer_times_2026.csv
    - assets/csv/qatar_prayer_times_2026.csv
    - assets/csv/bahrain_prayer_times_2026.csv
    - assets/csv/egypt_prayer_times_2026.csv
    - assets/csv/iraq_prayer_times_2026.csv
    - assets/csv/jordan_prayer_times_2026.csv
    - assets/csv/lebanon_prayer_times_2026.csv
    - assets/csv/morocco_prayer_times_2026.csv
    - assets/csv/palestine_prayer_times_2026.csv
    - assets/csv/syria_prayer_times_2026.csv
    - assets/csv/tunisia_prayer_times_2026.csv
    - assets/csv/yemen_prayer_times_2026.csv
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
    - family: Beiruti
      fonts:
        - asset: assets/fonts/Beiruti/Beiruti-Regular.ttf
        - asset: assets/fonts/Beiruti/Beiruti-Bold.ttf
          weight: 700
