import 'dart:convert';
import 'package:flutter/services.dart';

import 'country_name_resolver.dart';
import 'remote_city_catalog.dart';

// ── Country definitions ──────────────────────────────────────────────────────

class CountryInfo {
  final String key;
  final String arabicName;
  final String englishName;
  final List<String> cities;

  const CountryInfo({
    required this.key,
    required this.arabicName,
    required this.englishName,
    required this.cities,
  });
}

// ── Translations ─────────────────────────────────────────────────────────────
// Country labels come from assets/countries.json (single source of truth);
// city Arabic names come from assets/db_countries.json `cities`. Country + city
// *lists* come from db_city_lists.json; this file maps keys → labels.

class _CountryLabel {
  final String ar;
  final String en;
  const _CountryLabel(this.ar, this.en);
}

Map<String, _CountryLabel> _countryLabels = const {};
Map<String, String> _cityArabic = const {};

// ── DB-country state (populated after SQLite opens) ──────────────────────────

List<CountryInfo> _countries = const [];
Set<String> _dbCountryKeys = const {};

// ── World-city translations (assets/world_cities.json) ───────────────────────

Map<String, String> _worldCountryArabicByKey = const {};
Map<String, String> _worldCountryKeyByArabic = const {};
Map<String, String> _worldCityArabicByKey = const {};
Map<String, String> _worldCityEnglishByArabicKey = const {};

bool _loaded = false;

/// Loads translations, DB city lists, and world-city data. Call once at
/// startup. Country + city lists now come from [assets/db_city_lists.json]
/// (generated by tool/extract_city_lists.dart from the canonical SQLite DB)
/// so no bundled prayer_times.db is needed at runtime.
Future<void> loadCityTranslations() async {
  if (_loaded) return;

  // ── Unified country catalogue (single source of truth) ──────────────────
  // assets/countries.json: ISO-2 → { dbKey, ar, en }. Feeds every country
  // label consumer (DB labels, world labels, and the ISO tables in
  // country_name_resolver). No country name is duplicated in db_countries.json
  // or world_cities.json anymore — those hold city translations only.
  final countriesRaw = await rootBundle.loadString('assets/countries.json');
  final countriesData = jsonDecode(countriesRaw) as Map<String, dynamic>;
  final countryEntries = countriesData['countries'] as Map<String, dynamic>;

  final countryLabels = <String, _CountryLabel>{};
  final worldCountryArabicByKey = <String, String>{};
  final worldCountryKeyByArabic = <String, String>{};
  final englishByIso = <String, String>{};
  final dbKeyByIso = <String, String>{};
  countryEntries.forEach((iso, v) {
    final m = v as Map<String, dynamic>;
    final upperIso = iso.toUpperCase();
    final ar = m['ar'] as String;
    final en = m['en'] as String;
    final dbKey = (m['dbKey'] as String?)?.toLowerCase();
    worldCountryArabicByKey[upperIso] = ar;
    worldCountryKeyByArabic[ar] = upperIso;
    englishByIso[upperIso] = en;
    if (dbKey != null) {
      countryLabels[dbKey] = _CountryLabel(ar, en);
      dbKeyByIso[upperIso] = dbKey;
    }
  });
  _countryLabels = countryLabels;
  _worldCountryArabicByKey = worldCountryArabicByKey;
  _worldCountryKeyByArabic = worldCountryKeyByArabic;
  registerCountryTranslations(
    englishByIso: englishByIso,
    dbKeyByIso: dbKeyByIso,
  );

  // ── City Arabic names (English city name → عربي) ─────────────────────────
  final raw = await rootBundle.loadString('assets/db_countries.json');
  final data = jsonDecode(raw) as Map<String, dynamic>;
  _cityArabic = (data['cities'] as Map<String, dynamic>).map(
    (k, v) => MapEntry(k, v as String),
  );

  // Load DB country→cities list from the bundled JSON (replaces SQLite query).
  final cityListsRaw = await rootBundle.loadString('assets/db_city_lists.json');
  final cityListsData = (jsonDecode(cityListsRaw) as Map<String, dynamic>).map(
    (k, v) => MapEntry(k, (v as List).cast<String>()),
  );
  registerDbCountries(cityListsData);

  // ── Per-city Arabic/English for world cities (world_cities.json cities) ──
  final worldRaw = await rootBundle.loadString('assets/world_cities.json');
  final worldData = jsonDecode(worldRaw) as Map<String, dynamic>;
  final worldList = (worldData['cities'] as List).cast<Map<String, dynamic>>();

  final worldCityArabicByKey = <String, String>{};
  final worldCityEnglishByArabicKey = <String, String>{};
  for (final city in worldList) {
    final countryKey = (city['c'] as String).toUpperCase();
    final englishName = city['n'] as String;
    final arabicName = city['a'] as String;
    worldCityArabicByKey[_worldCityMapKey(countryKey, englishName)] =
        arabicName;
    worldCityEnglishByArabicKey[_worldCityMapKey(countryKey, arabicName)] =
        englishName;
  }
  _worldCityArabicByKey = worldCityArabicByKey;
  _worldCityEnglishByArabicKey = worldCityEnglishByArabicKey;

  _loaded = true;
}

/// Registers the DB-backed countries discovered at runtime from prayer_times.db.
/// [countryToCities] keys are DB country keys (lowercase); values are the
/// English city names stored in the `cities` table for that country.
///
/// Arabic/English labels are resolved from [_countryLabels]; if a key has no
/// translation, the key itself is shown (visible fallback, no crash).
void registerDbCountries(Map<String, List<String>> countryToCities) {
  final list = <CountryInfo>[];
  countryToCities.forEach((key, cities) {
    final label = _countryLabels[key];
    list.add(
      CountryInfo(
        key: key,
        arabicName: label?.ar ?? key,
        englishName: label?.en ?? key,
        cities: List.unmodifiable(cities),
      ),
    );
  });
  _countries = List.unmodifiable(list);
  _dbCountryKeys = Set.unmodifiable(_countries.map((c) => c.key).toSet());
}

/// Merges a remotely-published [catalog] over the bundled city lists so newly
/// published cities appear in the picker without an APK update.
///
/// ADDITIVE and safe by design:
/// - Never removes a bundled city (a bad publish can't wipe the catalog).
/// - Fills a *missing* Arabic name only — never overrides curated bundled ones.
/// - Registers countries the catalog introduces with their labels.
/// City lists are re-sorted by English name to match bundled ordering.
void mergeRemoteCatalog(RemoteCityCatalog catalog) {
  final byKey = <String, List<String>>{
    for (final c in _countries) c.key: [...c.cities],
  };
  final labels = <String, _CountryLabel>{..._countryLabels};
  final arabic = <String, String>{..._cityArabic};

  for (final country in catalog.countries) {
    final key = country.key.toLowerCase();
    final list = byKey.putIfAbsent(key, () => <String>[]);
    labels.putIfAbsent(
      key,
      () => _CountryLabel(country.arabicName, country.englishName),
    );
    for (final city in country.cities) {
      if (!list.contains(city.englishName)) list.add(city.englishName);
      arabic.putIfAbsent(city.englishName, () => city.arabicName);
    }
    list.sort();
  }

  _countryLabels = Map.unmodifiable(labels);
  _cityArabic = arabic;
  registerDbCountries(byKey);
}

// ── Public API ───────────────────────────────────────────────────────────────

List<CountryInfo> get kCountries => _countries;

Set<String> get kDbCountryKeys => _dbCountryKeys;

bool isDbCountry(String countryKey) =>
    _dbCountryKeys.contains(countryKey.toLowerCase());

/// Normalizes a country key to its canonical stored form:
/// - Matches DB countries case-insensitively (DB stores lowercase).
/// - Falls back to the uppercase ISO-2 code used by world_cities.json.
/// - Or reverse-resolves an Arabic country name to its world key.
String normalizeCountryKey(String key) {
  final trimmed = key.trim();
  if (trimmed.isEmpty) return trimmed;

  final lower = trimmed.toLowerCase();
  if (_dbCountryKeys.contains(lower)) return lower;

  final upper = trimmed.toUpperCase();
  if (_worldCountryArabicByKey.containsKey(upper)) return upper;

  return _worldCountryKeyByArabic[trimmed] ?? trimmed;
}

String countryLabel(String key, {String locale = 'ar'}) {
  final lower = key.toLowerCase();
  final dbLabel = _countryLabels[lower];
  if (dbLabel != null && _dbCountryKeys.contains(lower)) {
    // Arabic only for the 'ar' locale; every other UI language (en, fr, …)
    // shows the Latin name — better than Arabic for a French/English reader.
    return locale == 'ar' ? dbLabel.ar : dbLabel.en;
  }

  final normalizedKey = normalizeCountryKey(key);
  if (locale != 'ar') return resolveEnglishCountryName(normalizedKey);
  return _worldCountryArabicByKey[normalizedKey] ?? key;
}

String countryForCity(String cityKey) {
  for (final c in _countries) {
    if (c.cities.contains(cityKey)) return c.key;
  }
  return '';
}

/// DB is authoritative: [availableCities] already reflects the active country.
/// Kept as a pass-through so callers don't need to change.
List<String> citiesForCountry(String countryKey, List<String> availableCities) {
  return availableCities;
}

/// Latin labels for city keys that shipped misspelled. The key doubles as the
/// published data-file slug (`<slug>.json`) and as the value persisted in the
/// user's settings, so correcting the *key* would introduce a second city
/// rather than rename the existing one — the picker would then list the same
/// town twice on every install still carrying the old key. Correct the label
/// instead: key stays, display changes. Key → corrected Latin label.
const _latinCityLabels = {
  // Ghardaïa, Algeria — key shipped as 'Metilti Chamba'; the town is Metlili
  // Chamba / «متليلي الشعانبة» (reported by a resident). Arabic label is fixed
  // at its source in assets/db_countries.json.
  'Metilti Chamba': 'Metlili Chamba',
};

String cityLabel(String cityKey, {String locale = 'ar', String? countryKey}) {
  // Latin city names for every non-Arabic UI language (en, fr, …); only the
  // Arabic locale shows the Arabic city name.
  if (locale != 'ar') {
    if (countryKey != null) {
      final normalizedCountryKey = normalizeCountryKey(countryKey);
      final worldEnglish =
          _worldCityEnglishByArabicKey[_worldCityMapKey(
            normalizedCountryKey,
            cityKey,
          )];
      if (worldEnglish != null) return worldEnglish;
    }
    return _latinCityLabels[cityKey] ?? cityKey;
  }

  final dbArabic = _cityArabic[cityKey];
  if (dbArabic != null) return dbArabic;

  if (countryKey != null) {
    final normalizedCountryKey = normalizeCountryKey(countryKey);
    final worldArabic =
        _worldCityArabicByKey[_worldCityMapKey(normalizedCountryKey, cityKey)];
    if (worldArabic != null) return worldArabic;
  }
  return cityKey;
}

String _worldCityMapKey(String countryKey, String cityName) =>
    '${countryKey.toUpperCase()}::$cityName';
