import 'package:flutter/widgets.dart';
import '../features/quran/domain/entities/surah.dart';

/// Canonical Mushaf-ordered list of all 114 surahs with Arabic names and
/// Latin transliterations (used when the app locale is English).
/// Index = surah number - 1.
const List<Surah> kSurahs = [
  Surah(number: 1, nameAr: 'الفاتحة', nameEn: 'Al-Fatihah', ayahCount: 7),
  Surah(number: 2, nameAr: 'البقرة', nameEn: 'Al-Baqarah', ayahCount: 286),
  Surah(number: 3, nameAr: 'آل عمران', nameEn: 'Aal-i-Imran', ayahCount: 200),
  Surah(number: 4, nameAr: 'النساء', nameEn: 'An-Nisa', ayahCount: 176),
  Surah(number: 5, nameAr: 'المائدة', nameEn: 'Al-Ma\'idah', ayahCount: 120),
  Surah(number: 6, nameAr: 'الأنعام', nameEn: 'Al-An\'am', ayahCount: 165),
  Surah(number: 7, nameAr: 'الأعراف', nameEn: 'Al-A\'raf', ayahCount: 206),
  Surah(number: 8, nameAr: 'الأنفال', nameEn: 'Al-Anfal', ayahCount: 75),
  Surah(number: 9, nameAr: 'التوبة', nameEn: 'At-Tawbah', ayahCount: 129),
  Surah(number: 10, nameAr: 'يونس', nameEn: 'Yunus', ayahCount: 109),
  Surah(number: 11, nameAr: 'هود', nameEn: 'Hud', ayahCount: 123),
  Surah(number: 12, nameAr: 'يوسف', nameEn: 'Yusuf', ayahCount: 111),
  Surah(number: 13, nameAr: 'الرعد', nameEn: 'Ar-Ra\'d', ayahCount: 43),
  Surah(number: 14, nameAr: 'إبراهيم', nameEn: 'Ibrahim', ayahCount: 52),
  Surah(number: 15, nameAr: 'الحجر', nameEn: 'Al-Hijr', ayahCount: 99),
  Surah(number: 16, nameAr: 'النحل', nameEn: 'An-Nahl', ayahCount: 128),
  Surah(number: 17, nameAr: 'الإسراء', nameEn: 'Al-Isra', ayahCount: 111),
  Surah(number: 18, nameAr: 'الكهف', nameEn: 'Al-Kahf', ayahCount: 110),
  Surah(number: 19, nameAr: 'مريم', nameEn: 'Maryam', ayahCount: 98),
  Surah(number: 20, nameAr: 'طه', nameEn: 'Ta-Ha', ayahCount: 135),
  Surah(number: 21, nameAr: 'الأنبياء', nameEn: 'Al-Anbiya', ayahCount: 112),
  Surah(number: 22, nameAr: 'الحج', nameEn: 'Al-Hajj', ayahCount: 78),
  Surah(number: 23, nameAr: 'المؤمنون', nameEn: 'Al-Mu\'minun', ayahCount: 118),
  Surah(number: 24, nameAr: 'النور', nameEn: 'An-Nur', ayahCount: 64),
  Surah(number: 25, nameAr: 'الفرقان', nameEn: 'Al-Furqan', ayahCount: 77),
  Surah(number: 26, nameAr: 'الشعراء', nameEn: 'Ash-Shu\'ara', ayahCount: 227),
  Surah(number: 27, nameAr: 'النمل', nameEn: 'An-Naml', ayahCount: 93),
  Surah(number: 28, nameAr: 'القصص', nameEn: 'Al-Qasas', ayahCount: 88),
  Surah(number: 29, nameAr: 'العنكبوت', nameEn: 'Al-Ankabut', ayahCount: 69),
  Surah(number: 30, nameAr: 'الروم', nameEn: 'Ar-Rum', ayahCount: 60),
  Surah(number: 31, nameAr: 'لقمان', nameEn: 'Luqman', ayahCount: 34),
  Surah(number: 32, nameAr: 'السجدة', nameEn: 'As-Sajdah', ayahCount: 30),
  Surah(number: 33, nameAr: 'الأحزاب', nameEn: 'Al-Ahzab', ayahCount: 73),
  Surah(number: 34, nameAr: 'سبأ', nameEn: 'Saba', ayahCount: 54),
  Surah(number: 35, nameAr: 'فاطر', nameEn: 'Fatir', ayahCount: 45),
  Surah(number: 36, nameAr: 'يس', nameEn: 'Ya-Sin', ayahCount: 83),
  Surah(number: 37, nameAr: 'الصافات', nameEn: 'As-Saffat', ayahCount: 182),
  Surah(number: 38, nameAr: 'ص', nameEn: 'Sad', ayahCount: 88),
  Surah(number: 39, nameAr: 'الزمر', nameEn: 'Az-Zumar', ayahCount: 75),
  Surah(number: 40, nameAr: 'غافر', nameEn: 'Ghafir', ayahCount: 85),
  Surah(number: 41, nameAr: 'فصلت', nameEn: 'Fussilat', ayahCount: 54),
  Surah(number: 42, nameAr: 'الشورى', nameEn: 'Ash-Shura', ayahCount: 53),
  Surah(number: 43, nameAr: 'الزخرف', nameEn: 'Az-Zukhruf', ayahCount: 89),
  Surah(number: 44, nameAr: 'الدخان', nameEn: 'Ad-Dukhan', ayahCount: 59),
  Surah(number: 45, nameAr: 'الجاثية', nameEn: 'Al-Jathiyah', ayahCount: 37),
  Surah(number: 46, nameAr: 'الأحقاف', nameEn: 'Al-Ahqaf', ayahCount: 35),
  Surah(number: 47, nameAr: 'محمد', nameEn: 'Muhammad', ayahCount: 38),
  Surah(number: 48, nameAr: 'الفتح', nameEn: 'Al-Fath', ayahCount: 29),
  Surah(number: 49, nameAr: 'الحجرات', nameEn: 'Al-Hujurat', ayahCount: 18),
  Surah(number: 50, nameAr: 'ق', nameEn: 'Qaf', ayahCount: 45),
  Surah(number: 51, nameAr: 'الذاريات', nameEn: 'Adh-Dhariyat', ayahCount: 60),
  Surah(number: 52, nameAr: 'الطور', nameEn: 'At-Tur', ayahCount: 49),
  Surah(number: 53, nameAr: 'النجم', nameEn: 'An-Najm', ayahCount: 62),
  Surah(number: 54, nameAr: 'القمر', nameEn: 'Al-Qamar', ayahCount: 55),
  Surah(number: 55, nameAr: 'الرحمن', nameEn: 'Ar-Rahman', ayahCount: 78),
  Surah(number: 56, nameAr: 'الواقعة', nameEn: 'Al-Waqi\'ah', ayahCount: 96),
  Surah(number: 57, nameAr: 'الحديد', nameEn: 'Al-Hadid', ayahCount: 29),
  Surah(number: 58, nameAr: 'المجادلة', nameEn: 'Al-Mujadilah', ayahCount: 22),
  Surah(number: 59, nameAr: 'الحشر', nameEn: 'Al-Hashr', ayahCount: 24),
  Surah(number: 60, nameAr: 'الممتحنة', nameEn: 'Al-Mumtahanah', ayahCount: 13),
  Surah(number: 61, nameAr: 'الصف', nameEn: 'As-Saff', ayahCount: 14),
  Surah(number: 62, nameAr: 'الجمعة', nameEn: 'Al-Jumu\'ah', ayahCount: 11),
  Surah(number: 63, nameAr: 'المنافقون', nameEn: 'Al-Munafiqun', ayahCount: 11),
  Surah(number: 64, nameAr: 'التغابن', nameEn: 'At-Taghabun', ayahCount: 18),
  Surah(number: 65, nameAr: 'الطلاق', nameEn: 'At-Talaq', ayahCount: 12),
  Surah(number: 66, nameAr: 'التحريم', nameEn: 'At-Tahrim', ayahCount: 12),
  Surah(number: 67, nameAr: 'الملك', nameEn: 'Al-Mulk', ayahCount: 30),
  Surah(number: 68, nameAr: 'القلم', nameEn: 'Al-Qalam', ayahCount: 52),
  Surah(number: 69, nameAr: 'الحاقة', nameEn: 'Al-Haqqah', ayahCount: 52),
  Surah(number: 70, nameAr: 'المعارج', nameEn: 'Al-Ma\'arij', ayahCount: 44),
  Surah(number: 71, nameAr: 'نوح', nameEn: 'Nuh', ayahCount: 28),
  Surah(number: 72, nameAr: 'الجن', nameEn: 'Al-Jinn', ayahCount: 28),
  Surah(number: 73, nameAr: 'المزمل', nameEn: 'Al-Muzzammil', ayahCount: 20),
  Surah(number: 74, nameAr: 'المدثر', nameEn: 'Al-Muddaththir', ayahCount: 56),
  Surah(number: 75, nameAr: 'القيامة', nameEn: 'Al-Qiyamah', ayahCount: 40),
  Surah(number: 76, nameAr: 'الإنسان', nameEn: 'Al-Insan', ayahCount: 31),
  Surah(number: 77, nameAr: 'المرسلات', nameEn: 'Al-Mursalat', ayahCount: 50),
  Surah(number: 78, nameAr: 'النبأ', nameEn: 'An-Naba', ayahCount: 40),
  Surah(number: 79, nameAr: 'النازعات', nameEn: 'An-Nazi\'at', ayahCount: 46),
  Surah(number: 80, nameAr: 'عبس', nameEn: 'Abasa', ayahCount: 42),
  Surah(number: 81, nameAr: 'التكوير', nameEn: 'At-Takwir', ayahCount: 29),
  Surah(number: 82, nameAr: 'الانفطار', nameEn: 'Al-Infitar', ayahCount: 19),
  Surah(number: 83, nameAr: 'المطففين', nameEn: 'Al-Mutaffifin', ayahCount: 36),
  Surah(number: 84, nameAr: 'الانشقاق', nameEn: 'Al-Inshiqaq', ayahCount: 25),
  Surah(number: 85, nameAr: 'البروج', nameEn: 'Al-Buruj', ayahCount: 22),
  Surah(number: 86, nameAr: 'الطارق', nameEn: 'At-Tariq', ayahCount: 17),
  Surah(number: 87, nameAr: 'الأعلى', nameEn: 'Al-A\'la', ayahCount: 19),
  Surah(number: 88, nameAr: 'الغاشية', nameEn: 'Al-Ghashiyah', ayahCount: 26),
  Surah(number: 89, nameAr: 'الفجر', nameEn: 'Al-Fajr', ayahCount: 30),
  Surah(number: 90, nameAr: 'البلد', nameEn: 'Al-Balad', ayahCount: 20),
  Surah(number: 91, nameAr: 'الشمس', nameEn: 'Ash-Shams', ayahCount: 15),
  Surah(number: 92, nameAr: 'الليل', nameEn: 'Al-Lail', ayahCount: 21),
  Surah(number: 93, nameAr: 'الضحى', nameEn: 'Ad-Duha', ayahCount: 11),
  Surah(number: 94, nameAr: 'الشرح', nameEn: 'Ash-Sharh', ayahCount: 8),
  Surah(number: 95, nameAr: 'التين', nameEn: 'At-Tin', ayahCount: 8),
  Surah(number: 96, nameAr: 'العلق', nameEn: 'Al-Alaq', ayahCount: 19),
  Surah(number: 97, nameAr: 'القدر', nameEn: 'Al-Qadr', ayahCount: 5),
  Surah(number: 98, nameAr: 'البينة', nameEn: 'Al-Bayyinah', ayahCount: 8),
  Surah(number: 99, nameAr: 'الزلزلة', nameEn: 'Az-Zalzalah', ayahCount: 8),
  Surah(number: 100, nameAr: 'العاديات', nameEn: 'Al-Adiyat', ayahCount: 11),
  Surah(number: 101, nameAr: 'القارعة', nameEn: 'Al-Qari\'ah', ayahCount: 11),
  Surah(number: 102, nameAr: 'التكاثر', nameEn: 'At-Takathur', ayahCount: 8),
  Surah(number: 103, nameAr: 'العصر', nameEn: 'Al-Asr', ayahCount: 3),
  Surah(number: 104, nameAr: 'الهمزة', nameEn: 'Al-Humazah', ayahCount: 9),
  Surah(number: 105, nameAr: 'الفيل', nameEn: 'Al-Fil', ayahCount: 5),
  Surah(number: 106, nameAr: 'قريش', nameEn: 'Quraish', ayahCount: 4),
  Surah(number: 107, nameAr: 'الماعون', nameEn: 'Al-Ma\'un', ayahCount: 7),
  Surah(number: 108, nameAr: 'الكوثر', nameEn: 'Al-Kawthar', ayahCount: 3),
  Surah(number: 109, nameAr: 'الكافرون', nameEn: 'Al-Kafirun', ayahCount: 6),
  Surah(number: 110, nameAr: 'النصر', nameEn: 'An-Nasr', ayahCount: 3),
  Surah(number: 111, nameAr: 'المسد', nameEn: 'Al-Masad', ayahCount: 5),
  Surah(number: 112, nameAr: 'الإخلاص', nameEn: 'Al-Ikhlas', ayahCount: 4),
  Surah(number: 113, nameAr: 'الفلق', nameEn: 'Al-Falaq', ayahCount: 5),
  Surah(number: 114, nameAr: 'الناس', nameEn: 'An-Nas', ayahCount: 6),
];

/// Lookup by surah number (1..114). Returns null if out of range.
Surah? surahByNumber(int number) {
  if (number < 1 || number > 114) return null;
  return kSurahs[number - 1];
}

/// Locale-aware surah name resolver — picks the Arabic name when the
/// active locale is `ar`, otherwise the Latin transliteration.
String surahNameForContext(BuildContext context, int number) {
  final surah = surahByNumber(number);
  if (surah == null) return '';
  return surah.localizedName(Localizations.localeOf(context).languageCode);
}
